const express = require('express');
const router = express.Router();
const ticketController = require('../controllers/ticketController');
router.post('/tickets', ticketController.createTicket); 
router.get('/tickets', ticketController.getTickets); 
router.get('/tickets/filter', ticketController.getTickets);
router.get('/tickets/:id', ticketController.getTicketById);
router.put('/tickets/:id', ticketController.updateTicket);
router.patch('/tickets/:id/status', ticketController.updateStatus);
router.delete('/tickets/:id', ticketController.deleteTicket);
router.post('/tickets/assign', ticketController.assignTicket);
router.get('/tickets/user/:id', ticketController.getTicketsByUser);
module.exports = router;